/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/StudentStudy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/StudentStudy.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.785, 2.772, -3.574]} rotation={[1.571, 0, Math.PI]} scale={1.416}>
        <group position={[0, 0.015, 0]}>
          <mesh geometry={nodes.Circle002.geometry} material={materials['clock dark']} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials['clock white']} />
          <group position={[-0.001, 0, -0.106]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text000.geometry} material={nodes.Text000.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.052, 0, -0.093]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.092, 0, -0.054]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text002.geometry} material={nodes.Text002.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.106, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.093, 0, 0.052]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text004.geometry} material={nodes.Text004.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.054, 0, 0.092]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text005.geometry} material={nodes.Text005.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.001, 0, 0.106]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text006.geometry} material={nodes.Text006.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.052, 0, 0.093]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text007.geometry} material={nodes.Text007.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.092, 0, 0.054]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.106, 0, 0.001]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.093, 0, -0.052]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text010.geometry} material={nodes.Text010.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.054, 0, -0.092]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.Cylinder001.geometry} material={materials['clock white']} position={[0, 0.004, 0]} rotation={[0.001, 1.556, -0.001]} />
          <mesh geometry={nodes.Cylinder002.geometry} material={materials['clock dark.001']} position={[0, 0.005, 0]} />
          <mesh geometry={nodes.Cylinder003.geometry} material={materials['clock white']} position={[0, 0.002, 0]} rotation={[0, -0.915, 0]} />
          <mesh geometry={nodes.Plane001.geometry} material={materials['clock white']} position={[0, 0, -0.131]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Plane002.geometry} material={materials['clock white']} position={[0, 0, -0.131]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[0, 0.015, 0]}>
          <mesh geometry={nodes.Circle000.geometry} material={materials['plastic white']} />
          <mesh geometry={nodes.Circle000_1.geometry} material={materials.metal} />
        </group>
        <mesh geometry={nodes.Circle004.geometry} material={materials['Material.001']} position={[0, 0.015, 0]} />
      </group>
      <group position={[-2.279, 0, -2.263]} rotation={[0, 0.786, 0]} scale={[0.977, 1.222, 0.977]}>
        <group scale={1.795}>
          <mesh geometry={nodes.Plane.geometry} material={materials['Office Chair_Fabric']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Office Chair_Metal']} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['Office Chair_Painted Metal']} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials['Office Chair_Plastic']} />
        </group>
      </group>
      <group position={[-1.676, 1.327, -0.591]} rotation={[Math.PI, -0.494, Math.PI]} scale={0.207}>
        <group scale={[5.678, 5.971, 5.678]}>
          <mesh geometry={nodes.Circle001_1.geometry} material={materials.lamp_glass} />
          <mesh geometry={nodes.Circle001_2.geometry} material={materials.lamp_reflector} />
          <mesh geometry={nodes.Circle001_3.geometry} material={materials.lamp_light} />
          <mesh geometry={nodes.Circle001_4.geometry} material={materials.lamp_metal} />
        </group>
      </group>
      <group position={[0, 3.565, 0]} scale={3.616}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Cyan Leather']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Brown Polished Oak Wood']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['DENIM Ocean Indigo']} />
      </group>
      <group position={[-1.421, -0.044, -1.408]} rotation={[0, 0.804, 0]} scale={[1.342, 1.668, 2.476]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Aluminium} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Black Rubber']} />
      </group>
      <mesh geometry={nodes.Acer_Nitro_7_Gaming_Laptop.geometry} material={materials['Material.002']} position={[-1.459, 1.356, -1.579]} rotation={[Math.PI, -0.799, Math.PI]} scale={2.238} />
      <group position={[-2.102, 1.31, -1.065]} rotation={[Math.PI, -0.787, Math.PI]} scale={[2.44, 1.764, 1.764]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

useGLTF.preload('/StudentStudy.glb')
